#+TITLE:Tractatus

* Introduction
** Abstract
Many issues in philosophy arise out of
- Lack of knowledge regarding the principles of symbollism
- Misuse of language

To avoid this we require a logical structure to express propositions.
To build this understanding Wittgenstein discuss
1. The theory of knowled
2. The principles of physics
3. Ethics
4. The mystical
** Understanding the Intent of the Work
To understand Wittgenstein we must first understand the question he aims to
answer. It is not
- The meaning of what we intend to say through language
  - That is psychology
- It is not the relation between thoughts with words, sentences and what they mean
  - That is epistimology
- What the conditions are or truth hood or false hood of a sentence
  - That belongs to some not otherwise specified special science concerned with
    this question

Rather it is
- What relation must one fact (a sentence) must have with an other to be capable
  of being a symbol for the other.
** Perfect Language as an NP-Complete Problem
Ordinary everyday language is subjective and as such it would be beneficial to
have a way of gauging how subjective the use of language is. To do this the
requirements for a perfect language can be stated although a solution may not
neccessarily be created it is an NP-complete problem.

Ideally the language should be constructed such that
   - syntax forbids nonsensical proposition
   - words have an *atomic* meaning

The use of such a non-ambiguous use of language allows one to communicate the
ideals of what language aims to addres: the assertion or denial of facts.
** The Central Thesis of the Tractatus
In any langauge the structure of a factual sentece *must be linked to the
structure of the fact itself*. The commonality between proposition and fact
cannot be said in the language but only shown. In many ways this is similar in
spirit to Galois Theory or Godel's Incompletness theorem. In designing any
language there will always be axiomatic reprecussions.

Simple things should be assigned simple unique names. Things that are not simple
do not get a unique name, rather they are compounded by simple symbols into a
"complex". What is complex in the world is considered a fact which can either

- Stand alone
  - Sachverhalt
- Be combined to make other facts
  - Tatsache

Linguistic expression arises out of the many ways to convey the commonality
between fact and proposition in different languages much like the basis onto
which a geometric object can be projected into different subspaces.

Many of this should be in a certain elementary way obvious but a base in which
to ground an argument should be obviously true in order to build unquestionable
derivations from their axiomatic obviousness. However, even within the
obviousness it is easy to misconstruct symbolic relations. If we say "Alice
Loves Bob" we are ascerting a relation between the two atomic entites required
to identify Alice and Bob such that `aRb`. However, as a complex sign

- we must not say the complex sign "aRb" says that "a stands in a certain relation to b"
- we must say "a" and "b" stand in relation such that "aRb"

That is the complexity is bottom-up in such a way that the proposition is
*buit* not *subdivided*
** Pictures as Implicitly Logical Representations of Reality
The aim of language is to express an internal "picture" that arranges symbols in
such a way that they are logically cohesive. This pictured *need not be
graphical*, all of the following

- The gramophone
- The musical thought
- The sheetmusic
- The CD-ROM
- The waveform

are all derived from the same picture, just as

- Hansel
- Gretel
- The Witch
 
are all derived from the same story. The picture formed has symbols which stand
in relation to one another such that the picutre is not a picture if the symbol
is omitted from it in a gestalt manner. Arguing over what "Hansel" is makes no
sense out of context of what "Gretel" or "The Witch" is. No matter how wrong the
internal picture of the symbols is there must remain a commanility between the
structure of the picture and the structure of the fact itself. If I misremember
the story of Hansel & Gretel as, for example, dropping acorns rather than
breadcrumbs -- while being factually incorrect -- still continues to resembles
the logical structure of the picture. The unknown logical "constants" which hold
the story together cannot as a byproduct of the central thesis be expressed
through which the language of which the picture is expressed.

Thus arguing over the logical constants is meaningless in itself. Asking what
"dropping acorns" or "dropping breadcrumbs" or "what dropping is" *is in general
meaningless out of the context of the story*. Philosophy as a mode of arguing
over these logical constants thusly ends up as meaningless in itself. It *can
not* form logical propositions (because it is expressed through language), and
*is not* a science because science is composed of a structural framework formed
by combining logical propositions. Philosophy is not a thoery but rather an
*activity one does* to sharpen the boundaries of a pictoral representation of
the world. The result of philosophy is not a set of propositions but to make
propositions clear(er). The most one can hope to achieve via philosophical
disucssion is to disuade others from participating in philosophical discussion.

** Facts
While facts cannot be strictly defined they can be explained as what makes a
proposition true or false. As mentioned previously facts can be compose of facts
or be atomic (sachverhalt). The constituents of an atomic fact are referred to
as *simples* or *objects* that are a logical neccessity demanded by theory just
as the electron is demanded by particle physics. Anything *complex* -- that is
by definition something which cannot be a simple because not everything can be
simple as simples can form non-simple relations, as otherwise with no relations
there would be no facts on which to evaluate truthhood or falsehood. If we name
a complex, it is only meaningful in the context that it is factually true and it
is truthiness must arise out of the relation of its simples. Thus given
complexes are formed of facts, which must ultimately reduce to a set of atomic
facts, which when analyzed must be formed of simples: simples are the thing
which come logically first.

The world can be fully described if all simples and facts are known. It is not
enough to know only the simples. The proposition (truth or falsity) of an atomic
fact is an atomic proposition which is orthogonal to all other atomic
propositions. Compound propositions built out of atomic propositions are called
molecular. Molecular propositions which depend *only* on the truthood/falsehood
of a propostion $p$ are said to be truth functions. Like wise if a molecular
proposition of multiple propositions must be only dependent on the
truthood/falsehood of the multiple propositions. While the compmlexity of
language may suggest that there are things which exist other than truth
functions that depend solely on the boolean nature of an atomic fact, one can
not that any logical gate (and there for truth function) can be formed of NAND
gates. Thus, any logic can be constructed from a series of truth functions which
are dependant on one atomic proposition. Building upon the prior work of
logicians wittgenstein demonstrates that any fact is a truth function of atomic
propositions. This insight has interesting applications include that of
causality, the "fact" that the sun will rise tomorrow is in actuality not a fact
it is a hypothesis. Their is no reason why time should *cause* the sun to rise.

** Names
In a perfect language names are to be given on a one-to-one correspondance to
simples. In doing so it is not possible to enumerate all simples because as
there would have to exist some _logical property by which everything could be
named_. He critiques the notion of a self-identity and shows that the notion of
identity as someone of which differentiates an object from the discernable is
spurious. If something is discernable from nothig and two things are identical
if all traits are equal, then it is possible to accidentally discern two things
as equal, of which a perfect language would not allow for.

Given the totatily of things cannot be enumerated, things which assume the
truthood of that statement are therefore false. Thus saying "x is an object" is
to say nothing, for the set of things defined by simples cannot be unified by
objectictifying each as that would enforce the logical property by which
everything could be named. Rather a connection of the object to a property must
be applied (Heidegger screeches from far away) for the sentence to be
meaningful. To say "there are 3 objects" is meaningless and requires a
modification such as "there are 3 objects that are human" for example. From this
it follows that we can only define subsets of the world. Just as our vision is
not defined by vision boundaries so to is logic not definfed by logical
boundaries. Rather logic fills the world and we cannot make general assertments
about the totality of the world due to our finitness (pigeon hole principle).
Therefore we can never exclude anything from the realm of possibility because in
doing so we would define the limitations of the world as a whole as finite
beings. What we cannot think we cannot think and thus we cannot say what we
cannot think.

Solipism -- the belief that only the self can be known -- thus aims to reserve
judgement on the whole world except the self. However, the self I know is only
determined by the boundaires of the world which are decided by the boundaries of
my logical use of language. The metaphysical subject is not an object of the
world (note the modification "of the world") but a boundary within the world.
** Mysticism
Given everything cannot be fully expounded by language due to the fact that the
factual relations of simples cannot be described by the langauge itself, the
left over portion is understood as mysticism. Within this mysticism all of
philosophy is contained. The proper way to teaching philosophy would be to teach
science and leave the student to explore the philosohpical ramifications before
being shown that they are inhernetly meaningless. However, the grandure and
weight of this statement relies on the assertion that things can only be shown
which is an extreme amount of faith to place on the correct nature of one
concept. Still all parts of the logical framework are extremely self-consistent,
more so than average that understanding the framework of Wittgenstein regardless
of the inherent beliefs of the reprecussions is an important undertaking for any
philosohper. Bertrand Russel's main argument against Wittgenstein is
life-experience.
* Preface
The summary of the book can be stated as follows:

_What can be said at all can be said clearly; and whereof one cannot speak
thereof one must be silent._

The book was written for personal pleasure. There will be no citations or
references except for two in the preface commending Frege and Bertrand Rusell.
* Chapter 1
** Statement of Core Axioms
1. The world is made of facts not objects.
2. If an object is to exist it must exist as some part of a fact without accident.
3. The totalilty of logical facts defines the world and the world divides into facts.
* Chapter 2
** Objects Embedded in Factual Space
Just as we cannot spatially represent an object with embedding it in space so to
can an object not be created in connection with other objects factually. If one
can think of an object in the context of an atomic fact it cannot be thought
outside of the possibility of the context of that fact.

To know an object is to know all it's possibilities in occurance in atomic
facts, as every possibility must be available internally to the object itself
with no new possibilities able to be discovered. If all objects are known then
it follows all atomic facts are known.

Each thing is in a space of atomic facts. One can imagine the space empty but
the thing without the space.

*** Personal Thought:
In vacuums where the probability of a particle/anti-particle pair can be
spontenaously created and annihilited as a possibility the existance of these
objects can only exist in the framework of physics that bring the objects in to
existence with knowledge of the atomic facts that gvoern their reciprocity.

*** A Simple Example:
 An object must have some colour. It doesn't have to be red but it exists in a
 space of colours defined by atomic facts. We can think of an object indepdent
 of its colour but to give it colour requires their to be a colour space to give
 it from. It exists within a so called colour space.
** Objects are Defined by all the Ways they can be Described
An object can be potentially represented in many different ways. An object is
defined by all the ways it can be represented. The way an object is found to be
presented is the form of the object.
** Objects as the Substance of the World
Objects are the substance of the world and cannot be subdivided. They can only
be compounded into complexes that which can be analyzed by their composing
objects. If we imagine a world with no substance and therefore no objects then
whether a proposition made sense could only purely depend on other propositions.
This infinetely regressive argument demonstrates that one could not therefore
sketch out the world.

No matter how different the mental representation of a world to someone is from
the real world it must to some degree bear a commanility with the real world
given it is a representation. This is not tautological but rather just obvious.
This fixed form of things is just objects.

The substance of the world being composed of objects can only be a form of the
objects and not of material property. For it is the propositions in which an
object is configured that determine any potential material property. Roughly
speaking objecst are colourles, they do not differentiate by being different
colours but because they are different. Either a thing has properties that no
other thing has and thus I can readily distinguish it or it is a duplicate in
the totality of it's properties. For if nothing distinguishes an object it
cannot be distinignuished.

For the world to be of fixed form there must be objects. The fixed, existing and
object are one. Objects do not change they are immutable, it is only their
configuration that can represent variation in the form of the world. The
configuration of the objects froms an atomic fact.

Objects hang together through a graph of relations the form is the possibility
of the structure.
** Atomic Facts
The totality of atomic facts determines the non-existance of atomic facts which
together constitute reality. The existence is also called a positive atomic fact
and non-existane a negative atomic fact. All atomic facts exist indepdently of
each other and thus whether one fact exists or not does not allow us to infer
the existance of another.

The sum total of reality is the world.
** Pictures as a Form of Reality
Facts create pictures which arrange them within a logical space -- that is the
existance of non-existance of facts as a model of reality. Objects are the
elements of the picture and the picture is constitutde by the arrangment of
elements within it. The picture is a fact itself.

The elements of a picture and their connections constitute the struture of the
picture that it has taken form of. In this way pictures are a mental
approximation of reality as a measure. Does the state of affairs fit the
picture?

*** Personal Thought
Consider asking yourself *"Does it fit within the picture?"* what other are we
asking than ourselves if the picture constitutes the object it becomes a poor
representation of the reality thus understood?
** What Pictures can Represent Through Their Relations
The relation of elements within the picture also belong to the picture. This
pictoral relationship consists of the correlation of the elemtents of a picture
with things. These correlations are what match it with reality and if a fact is
to be a picture it must have something with what the picture is depicting.
Something must be identical between the picture and reality which acts as a form
of representation. The picture can represent the reality. A spatial picture can
depict anything spatial, a coloure picture anything coloured

The picture however cannot represent it's own pictoral form. It can only
*display it to the indvidual*. A picture represents its subject from outside of
it. Thus it can either be displayed correctly or incorrectly. A picutre cannot
plaace itself outside of the form the representation that it expresses as
otherwise the picture could not display something because that thing would have
to be formless and indistinguashble form the boundary of the picture the
audience views.

Every picture rightly or wrongly displayed must contain a logical form to
approximate it's form of reality. A picture whose pictoral form is logical is
called a logical picture. Every picture is also a logical picture, however on
the other hand not every picture is of the spatial form.

The picture represents reality by represent what atomic facts exist and do not
exist for a given situation of objects. It is a possible state of affairs set in
logical space, either rightly or wrongly. It need not correspond to reality to
represent it always represents its _sense_ that potentially aligns with reality.
In it's alignment of sense with reality is where its truthood or falsehood
consists. Thereby to ascertain whether a picture is true or false it must be
comapred against reality. It cannot be determined by the picture alone if it is
true. There is no picture that has an a priori truthhood.
* Chapter 3
** Expressing illogical opinion is impossible
To present anything in language illogically is impossible. To express illogical
language is to present contradict geomtery with a set of coordinates, it is
impossible. What is presented through these coordinates of points is the truth
which the set of points belong to but not vice versa. A cone may be sliced as a
circle, oval, point, triangle or parabola but that does not mean that any of
those when presented are exclusive to the cone. Mathematically it is an
unconstrained system.
*** Original Thought
Penrose's Triangle, or other geometrical are not violations of space. The face
we can group them as apparant violations of space in itself are confined to the
limitations of 3D projection onto a 2D manifold, for example isometry.
** The Propositional Sign as an Articulate Fact
A proposition constrcuted out of relations of simples therefore is similar to
the projection of an abstract body onto a lower dimensional plane into a set of
points. Understanding the ways in which a projection can be generalized under
constraints is the sense of a proposition. This projective relation to the world
through langauge is the expression of though that Wittgenstein call's the
Propositional Sign.

Just as these set of points has order so to does the propositional sign. It is
not merely a mixing of objects just as music is not a mixing of notes. This is
to say only facts can express a sense a class of names cannot. Style covers over
the propostional sign as when written gives the appearance of "just words".
*** Original Thought
Beat poetry seems to be an example that directly contradicts Wittgenstein here.
It is possible to evoke emotion by beat poetry. How abstract a "sense" beat
poetry conveys is up for debate. However, this would probably be expressed as
style from Wittgenstein.

Furthermore speech-acts to my knowledge seem to fly in the face of this. "I do"
is not a fact and stand alone in a langauge it makes no sense out of the
contextual understanding of marriage. The statement has obvious religous and
legal conotations that are communicated to an audience despite not being a fact.
** False assignment of names
When written it is easy to mistake a complex for a named simple. We cannot say
"aRb" says that "a" stands in a certain relation to "b", we must say "a" stands
in a certain relation to "b" such that "aRb". That is we can _describe_ a state
of affairs but not _name_ them.

- Names are reserved for objects which interpreted geometrically are points
- Propositions resemble arrows between points, they have sense

Objects I can _name_, signs I can only _represent_. We can speak _of_ signs but
not assert them. A proposition can only tell us _how_ not _what_. How does "a"
stand in relation to "b", not what is "aRb"?
*** Original Thought
- How does a char sit next to a table
  - Not what is a chair sitting next to a table
- How does a calorie affect body mass
  - Not what is a calorie affeting body mass
** Language as an Underconstrained System
A Propositional signs/elements are undersconstrained collections of points
projecting a complex/fact that is formed of simples/objects. Through geometric
analogy a set of points with arrow-like relations between them form an
underconstrained projection of a higher dimensional analogue. We can still sense
the truth through the signal but not understand the truth
*** Original Thought
Explaining the rules of pacman do not enable one to visualize how pacman looks
like on a torus.
** Names and Completely Analyzed Propositional Signs
Our thoughts can be expressed in such a way that the _objects of our thoughts_
are expressed as signs. These objects of our thoughts are referred to as _simple
signs_ by Wittgenstein or more intuitively _names_. When a proposition is
expressing them he uses the bi-gram _completely analyzed_. The name means the
object and the object _is_ it's meaning. How these _simple signs_ are arranged
describe and correspond to the state of affairs. The description of this state
of affairs is either correct or incorrect.

If we consider the difference between

- a simple sign that is simply it's object
- a sign that is a description of a complex

each signify in their own way. What does not get expressed by the name of the
the complex must be shown in it's application. What it conceals the application
declares.

To elucidate we must understand all the simple signs of a completely analyzed
proposition. Thus we must understand al the simple signs before we can achieve
elucidation

*** Original Thought
A child begins to describe a state of affairs by simply naming the objects in
them. They point to an object and say the name of what they are pointing
towards. How the objects are configured is highly nuanced however. If a child
sees Santa Claus and their Mom such that Mommy is kissing Santa Claus in the
realtion "aRb" bwhere "a" is their Mom which stands in relation to "b"
santa-claus such that they are kissing the nuance of the relation between "a"
and "b" is indeed quite complex. However while the signage of the world reflects
_their_ objects of thought to an adult santa claus does not exist. Thus the
sentence aR(cRb) describes their mom beside a man dressed as santa-claus
kissing, the joke being that santa-claus is the kids dad.

Here the child has a less perfect "language" because they were equipped to only
describe what they saw to a certain accuracy which included a definite entity
such as santa-claus not _how_ the state of affairs truly appeared (i.e. a man
dressing like santa-claus). The child's description is further away from the one
and only one completely analyzed proposition available by those who understand
the simplesigns of which santa does not belong.
** Constants and Variables
Only propositions can have sense and names can only have meanings within their
respective propositions. The perfect language describes all _relations_ of
objects, objects cannot exist without _relations_ given objects are defined by
the totality of _relations_ (Org notes 2.2). The parts of a proposition that
convey the sense are called _expressions_ (or a _symbol_).

Note that because a proposition has a sense the proposition itself is an
expression. What propositions share in common are expressions. Like objects
being defined in all the ways they can be described (Org notes 2.2) an
expression presupposes the form of all the forms of propositions in which it can
occur. In this form the expression is _constant_ and everything else _variable_.
** Symbols and Sign
An expression is presented by a variable the values of which the variable can
take on being defined by the propositions which can contain the expression. An
expression only has meaning within a proposition

3.313-3.323 is quite hard to parse

"Green is green" where the first is a proper noun and the last an adjective the
words do not only have different meanings but different _symbols_ the _sign_ is
the part of the _symbol_ that humans can see using one of their five senses.
Thus logically the color green which we see or the word "green" which we hear
from someone speaking orally or the written word "green" are all symbols. Two
different symbols can still have the same sign but they _signify_ in different
ways.

_In everyday language the same word signifies in multiple ways_

Thus to avoid errors we need a symbolism that obeys rules of a logical grammar.

The sign only has a logical form when when embedded in logic (logical syntactic
application) if the sign is superfluous/not necessary then it is meaningless.
This is what Occam's Razor describes.
** Accidental Features
3.334-3.421 is also quite dense but it seems like Wittgenstein is aiming to give
a robust description of why objects _cannot_ be understood in isolation they
must be viewed in the totality of the world and their connections.

Definitions of words that appear to isolate a subject are merely rules to
translate between language, this is what all words have in common.

** Thoughts
The proposition determines a point in logical space. However to know the
proposition one must understand the whole of the logical space given the
proposition is understood by it's connections.

To identify a proposition so as in a way to demarkate off a part of logical
space from it is to be in denial from the proposition.

Propositional sign is the thought (somehow)
* Chapter 4
** Propositions as reality
The totality of propositions constitue a language with which to describe
reality. Humans for whatever reason are able to speak colloquially without
neccessairly understanding correct propositions.

At first glance propositions does not seem to be a representation of reality. A
musical score does not appear to encode music. However it is clear that they do
form a picture of some abstract reality that they serve as the projection of.
When understood intimately this pictoral nature is not marred by apparant
irregularities such as a flat or sharp demarcation on a note. It encodes the
logical structure present just as a gramophone records the sharp and the flat by
the groves within it.

Propositions show their senses. Consider hieroglyphics and how we can connect
their pictoral nature with that of reality. They constitute a reality they show
that one either confirms or denies which in turn becomes that individuals
reality. Held together by a logical scaffolding a proposition can allow an
individual to falsely believe in a reality that does not exist and furthermore
draw conclusions from it's false proposition. Understanding a proposition is to
understand what a proposition means if it is true. To understand what "you have
a terminal illness" means is to understand what the ramifications of that
statement are _if true_. This _does not mean you neccessarily have a terminal
illness_, you can _falsely_ believe in your impending death and draw conclusions
accordingly.
** The Atomic Fact
To learn new propositions it is essential that they can communicate new _senses_
through old propositions. Old words and relations must give rise to new
relations. These relations, words, and objects are the pictoral representation
of the state of affairs. They are like an experiment which synthetically unites
a variety of objects to hold them in relation with one and another to determine
the truthhood of that state of affairs. Names describe things which are related
and hang together cohesively to present a state of affairs which is like a
living picture. What the picture communicates is the atomic fact.
** The Sense of a Proposition
The proposition is dependent on the naming of objects to present the atomic
fact, but the _logic of the facts cannot be represented_

For example consider two propositions of which one "p" signifies in a true way
what "~p" signifies in the false way. One cannot infer correctly from "~p" as
"p" is only understood _if it were true_. However it is important to note that
nothing in reality can constitute the logic of the symbol "~" between the two
cases. While "p" and "~p" have different sense they share the same reality.

*** Original Thought
"A jaguar is behind you", both share the sense of the same reality that a jaguar
is _literally_ behind you causing you to be scared. However the truthood of the
statement cannot be inferred by imagining the jaguar _not_ behind you. It is
that of the jaguar being behind you and then that being negated -- but that
negation corresponds to nothing in reality as the jaguar not being behind you or
being behind you are simply logical descriptions of it's comparison with
reality.

This original thought is actually expounded (albeit more mathematically)
immediately following the discussion of "p" and "~p" which is a sign of
alignment between what I am comprehending and Wittgenstein's thought. However
Wittgenstein very tersly points out that the sense of the proposition is that of
understanding what it would be to evaluate it's truthood.

To understand "A jaguar is behind you" is to understand _how to evaluate_ if a
jaguar is behind me and in this way I have already sensed from the proposition.
** Denials of Proposition
To deny a proposition is to not evaluate the truthood. Rather it is to point
out that a proposition that describes reality must exist not in the space
occupied by the denied proposition. That one can deny the denial of a
proposition is evidence that this must be a proposition as the assertion of a
proposition corresponding with reality cannot be sensed for it asserts is the
sense itself with reality
** Philosophy as an activity
The totality of true atomic facts constitutes all of the natural sciences.
Philosophy is not a science it is an activity focused on elucidation to clarify
propositions and demaarcate what is thinkable and what is unthinkable. It is the
logical clarification of thought.
** Everything can be said clearly
Everything which can be thought can be thought clearly. Anything which can be
said can be said articulately.

*** Personal Thought
I'm guessing this will be the sense of this text that P.I. tries to dismantle.

Or perhaps slightly below what he tries to hit home

What _can_ be shown _cannot_ be said
** Internal Properties and Formal propositions
There is a certain sense of formal relation between objects and atomic facts.
A property is said to be internal if it is _unthinkable_ that an object would
not have the property.

That a bright shade of blue compared to a darker shade of blue stand _eo ipso_
(by the very act or quality; thereby) in the internal relation of what is
lighter and what is darker. It is unthinkable to conceive of these shades
should not stand in this relation.

Internal properties are represented in language by the propositions presenting
them. Thus a series of propositions are connected by interal properties that
chain them together aRb is equivalent to:

- "\therexists x: aRx xRb"
- "\therexists x, y: aRx xRy yRb"

this allows us to discuss formal propositions

The formal relation of the integer number line is an internal relation in that
it is unthinkable to consider the sequence of numbers without them within a line.
** The Object Psuedo-Concept
The existance of "objects" by which internal properties are held between
propositions is rightly said as the part "\therexists x, y" where "x" and "y"
are the psudeo-objects. The psudeobjects must be applied in relation to the
simples "a" and "b" otherwise they have no sense: "\therexists x: xRb" is
senseless.  The psudeo-object must be applied to have any sense. One cannot say
"there are 100 objects" or "thereare alphanull objects" or "there are objects"
one must specify the simple or name of the complex.

*** Original thought
God it feels like Wittgenstein is describing abstract syntax trees. I imagine
somebody must have written about this. Maybe that's why Wittgenstein felt he was
so misunderstood... he was trying to describe how to write ASTs to people who
didn't even have a sense of a computer works... shit this is pretty good.

the name applied to an object in an AST is not the object itself but rather a
symbol that indicates something which at it's core is of a boolenan nature --
the simple or the object. At it's core these are either true or false in their
binary representation. Of course we do not just write booleans, we write
integers, floats, strings, chars all of which are expressed as a name for a
specified relations of booleans on the very low level.

We combing propostions to form an AST that approximates a picture of reality
that is evaluated on it's final output at the end. The relations of objects are
bound to the primary instructions like `+ - / *` in lisp etc and we as humans
some where in this we generalize on top things like `map` or `reduce` things
that do not exist in reality but connect propositions in such a way that at the
end they can be verified against reality (this argument is weak).

I like this a lot, reflect and come back.

The atomic fact is the pictoral representation of reality for a the subtree of
an AST.
** Attack of Monoisum Dualism
Because one cannot say there is "there are two objects" as it is senseless one
cannot say there "Therea re two parts of man mind and body"
** Truth Tables
Wittgenstein goes ham on discussing truth tables the core takeaway of which are
two extreme cases. Those which exist when the two propositions agree in all
possibilities of a truth table which compares them denoted as _tautological_ and
those that disagree in all possibilities denoted _self-contradictory_.

A tautology shows what it says and a contradiction shows that it says nothing.

Wittgenstein says that the events of the future cannot be predicted by the
events of the present. I don't know if I'm going too hard on the lisp and him
just being an early CS dude analogy here but it sounds a lot like Turing
Complete. Research this.
* Chapter 5
** Limits of Language
Logic precedes everything and if language is meant to convey logic as we
understand it then the limit of our world is limited by language

We cannot say what we cannot think therefore we cannot think what we cannot say
